//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igra.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Igra.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grats!.
        /// </summary>
        public static string GratsMsg {
            get {
                return ResourceManager.GetString("GratsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level must be from 1 to 8!.
        /// </summary>
        public static string LevelNumberValidationError {
            get {
                return ResourceManager.GetString("LevelNumberValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL.
        /// </summary>
        public static string MainPageTitlePrefix {
            get {
                return ResourceManager.GetString("MainPageTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High
        ///score.
        /// </summary>
        public static string MenuHighScore {
            get {
                return ResourceManager.GetString("MenuHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string MenuInstructions {
            get {
                return ResourceManager.GetString("MenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New 
        ///game.
        /// </summary>
        public static string MenuNewGame {
            get {
                return ResourceManager.GetString("MenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume game.
        /// </summary>
        public static string MenuResumeGame {
            get {
                return ResourceManager.GetString("MenuResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        public static string NewGameQuestion {
            get {
                return ResourceManager.GetString("NewGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionLanguage {
            get {
                return ResourceManager.GetString("OptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning mode.
        /// </summary>
        public static string OptionLearningMode {
            get {
                return ResourceManager.GetString("OptionLearningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sum.
        /// </summary>
        public static string OptionShowSum {
            get {
                return ResourceManager.GetString("OptionShowSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string OptionSoundEffects {
            get {
                return ResourceManager.GetString("OptionSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start level:.
        /// </summary>
        public static string OptionStartLevel {
            get {
                return ResourceManager.GetString("OptionStartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string OptionVibrate {
            get {
                return ResourceManager.GetString("OptionVibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made to top 10. Enter your name:.
        /// </summary>
        public static string PlayerNameTitle {
            get {
                return ResourceManager.GetString("PlayerNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum:.
        /// </summary>
        public static string SumText {
            get {
                return ResourceManager.GetString("SumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s up!  .
        /// </summary>
        public static string TimeUpMsg {
            get {
                return ResourceManager.GetString("TimeUpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TitleOptions {
            get {
                return ResourceManager.GetString("TitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
